Spur/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from todoapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls', namespace="todoapp")),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('signup/<str:token>', views.signup, name='signup'),
    path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate_account/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.ActivateAccountView.as_view(), name='activate_account'),
    # path('accept_invite/<str:token>', views.accept_invite, name='accept_invite')
]

todoapp/urls.py
from . import views
from todoapp.api import resources
from django.urls import path
from django.conf.urls import include, url
app_name = 'todoapp'

urlpatterns = [
    path('', views.my_goals, name='my-goals'),
    path('projects/show/<int:goal_id>/', views.show_projects_for_goal, name='show_projects_for_goal'),
    path('tasks/edit_task/<int:project_id>/', views.edit_task, name='add_new_task'),
    path('tasks/edit_task/<int:project_id>/<int:task_id>/', views.edit_task, name='edit_task'),
    path('projects/edit_project/<int:goal_id>/',views.edit_project, name='add_new_project'),
    path('projects/edit_project/<int:goal_id>/<int:project_id>',views.edit_project, name='edit_project'),
    path('today/', views.show_todays_tasks, name='show_todays_tasks'),


    # path('tasks/edit/<int:task_id>', views.edit_task, name='edit_task'),
    url(r'^api/manage_task/$', resources.manage_task, name='manage-task'),
    url(r'^api/manage_project/$', resources.manage_project, name='manage-project')
]

todoapp/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.dispatch.dispatcher import receiver
from django.db.models.signals import post_save
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone

class UserInfo(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='userinfo')
    email_confirmed = models.BooleanField(default=False)
    image_url = models.URLField(blank=True, null=True)

class Goal(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="user_goals")
    name = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    order_number = models.IntegerField(blank=True, null=True)
    COMPLETE = 'C'
    ACTIVE = 'A'
    DELETED = 'D'
    STATUS = [
        (COMPLETE, 'complete'),
        (ACTIVE, 'active'),
        (DELETED, 'deleted')
    ]
    status = models.CharField(
        max_length=1,
        choices=STATUS,
        default=ACTIVE
    )
    # dream, work, health, family, leisure, other
    # category =


class Project(models.Model):
    goal = models.ForeignKey(Goal, on_delete=models.SET_NULL, null=True, related_name="goal_projects")
    name = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    deadline = models.DateTimeField(blank=True, null=True)
    goal_kudos = models.PositiveIntegerField(blank=True, null=True, default=1, validators=[MinValueValidator(1), MaxValueValidator(100)])
    COMPLETE = 'C'
    ACTIVE = 'A'
    DELETED = 'D'
    STATUS = [
        (COMPLETE, 'complete'),
        (ACTIVE, 'active'),
        (DELETED, 'deleted')
    ]
    status = models.CharField(
        max_length=1,
        choices=STATUS,
        default=ACTIVE
    )

class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, related_name="project_tasks")
    name = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    deadline = models.DateTimeField(blank=True, null=True)
    not_until = models.DateTimeField(blank=True, null=True)
    order_within_project = models.IntegerField(blank=True, null=True)
    duration_minutes = models.IntegerField(blank=True, null=True)
    COMPLETE = 'C'
    ACTIVE = 'A'
    DELETED = 'D'
    STATUS = [
        (COMPLETE, 'complete'),
        (ACTIVE, 'active'),
        (DELETED, 'deleted')
    ]
    status = models.CharField(
        max_length=1,
        choices=STATUS,
        default=ACTIVE
    )

    @property
    def score(self):
        if self.project.goal_kudos:
            score = self.project.goal.order_number / self.project.goal_kudos
        else:
            score = self.project.goal.order_number

        days_to_deadline = None
        if self.deadline:
            # count days to deadline
            now = timezone.now()
            delta = self.deadline - now
            days_to_deadline = delta.days
            print(days_to_deadline)
            print(self.name)
            score = score * (days_to_deadline/10)

        return score

    @property
    def duration_string(self):
        if self.duration_minutes:
            hours = self.duration_minutes // 60
            minutes = self.duration_minutes % 60
            return ''.join([str(hours), "h ", str(minutes), "m"])
        else:
            return ''

    @property
    def follows_task_with_notuntil(self):
        now = timezone.now()
        if Task.objects.filter(status="A", project=self.project, order_within_project__lt=self.order_within_project, not_until__isnull=False, not_until__lt=now).exists():
            return True
        else:
            return False

    def is_past_due(self):
        now = timezone.now()
        if self.deadline:
            return now > self.deadline
        return False

    def not_until_expired_or_none(self):
        now = timezone.now()
        if self.not_until:
            return now >= self.not_until
        return True

    def rearrange_tasks_order(self):
        # if not self.order_within_project:
        #     self.order_within_project = 1
        #     self.save()
        this_task_order = self.order_within_project
        all_tasks = Task.objects.filter(project=self.project, status__in=['A']).order_by(
            'order_within_project').exclude(id=self.id)
        other_tasks_count = all_tasks.count() + 1
        if not self.order_within_project or this_task_order > other_tasks_count > 0:
            this_task_order = other_tasks_count
            self.order_within_project = other_tasks_count
            self.save()
        counter = 1
        for task in all_tasks:
            if task == self:
                continue
            if counter == this_task_order:
                counter = counter + 1
            task.order_within_project = counter
            task.save()
            counter = counter + 1

@receiver(post_save, sender=User)
def save_user_info(sender, instance, **kwargs):
    instance.userinfo.save()

todoapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm, TextInput, DateInput, NumberInput, TimeInput, Select
from .models import Task, Project



class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    # last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254, required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'password1', 'password2', )


class Task(ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'deadline', 'not_until', 'order_within_project', 'duration_minutes', 'status']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'deadline': DateInput(attrs={'class': 'form-control datepicker'}),
            'not_until': DateInput(attrs={'class': 'form-control datepicker'}),
            'order_within_project': NumberInput(attrs={'class': 'form-control'}),
            'duration_minutes': TimeInput(attrs={'class': 'form-control'}),
            'status':  Select(attrs={'class': 'form-control'})
        }
        help_texts = {

        }

    def __init__(self, *args, **kwargs):
        super(Task, self).__init__(*args, **kwargs)
        # self.fields['order_within_project'].required = True
        self.fields['name'].required = True
        self.fields['duration_minutes'].required = True


class Project(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'deadline', 'goal_kudos', 'status']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'deadline': DateInput(attrs={'class': 'form-control datepicker'}),
            'goal_kudos': NumberInput(attrs={'class': 'form-control'}),
            'status':  Select(attrs={'class': 'form-control'})
        }
        help_texts = {

        }

    def __init_(self, *args, **kwargs):
        super(Project, self).__init__(*args, **kwargs)
        self.fields['name'].required = True
        self.fields['goal_kudos'].required = True

todoapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Goal, Task, Project
from django.contrib.auth import login, authenticate, logout
from todoapp.forms import SignUpForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from todoapp.tokens import account_activation_token, generate_invite_token
from django.utils.encoding import force_bytes, force_text
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponseForbidden,HttpResponse
import json
import datetime
import sendgrid
from sendgrid.helpers.mail import *
import os
from django.views import generic, View
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse_lazy, reverse
from .calculations import calculate_todays_tasks

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import Task as TaskForm
from .forms import Project as ProjectForm


sg = sendgrid.SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
from_email = Email("yulia@yuliashea.com")


# Create your views here.
@login_required
def my_goals(request):
    goals = Goal.objects.filter(owner=request.user).order_by('order_number')
    return render(request, 'todoapp/goals.html', {'goals': goals})
    # return render(request, 'todoapp/goals.html')


def show_todays_tasks(request):
    today_data = calculate_todays_tasks()
    return render(request, 'todoapp/tasks_for_today.html', {'today_data': today_data})


def show_projects_for_goal(request, goal_id):
    projects_data = []
    goal = Goal.objects.get(id=goal_id)
    goal_projects = goal.goal_projects.filter(status="A").order_by('-goal_kudos')
    for project in goal_projects:
        project_data = {
            'project': project,
            'tasks': project.project_tasks.all().order_by('order_within_project')
        }
        projects_data.append(project_data)

    return render(request, 'todoapp/projects.html', {'goal': goal, 'projects_data': projects_data})


def edit_task(request, project_id=None, task_id=None):
    if request.method == 'GET':
        if not task_id:
            task_form = TaskForm()
        else:
            task = Task.objects.get(id=task_id)
            task_form = TaskForm(instance=task)

    elif request.method == 'POST':
        if not task_id:
            task = Task(project_id=project_id)
        else:
            task = Task.objects.get(id=task_id)
        task_form = TaskForm(request.POST,instance=task)
        if task_form.is_valid():
            new_task = task_form.save()
            new_task.rearrange_tasks_order()
            return HttpResponseRedirect(reverse_lazy('todoapp:show_projects_for_goal', kwargs={'goal_id': task.project.goal_id},
                                current_app='todoapp'))
    return render(request, 'todoapp/task.html', {'form': task_form, 'project_id': project_id, 'task_id': task_id})


def edit_project(request, goal_id=None, project_id=None):
    if request.method == 'GET':
        if not project_id:
            project_form = ProjectForm()
        else:
            project = Project.objects.get(id=project_id)
            project_form = ProjectForm(instance=project)

    elif request.method == 'POST':
        if not project_id:
            project = Project(goal_id=goal_id)
        else:
            project = Project.objects.get(id=project_id)
        project_form = ProjectForm(request.POST,instance=project)
        if project_form.is_valid():
            new_project = project_form.save()
            return HttpResponseRedirect(reverse_lazy('todoapp:show_projects_for_goal', kwargs={'goal_id': project.goal_id},
                                                     current_app='todoapp'))
    return render(request, 'todoapp/edit_project.html', {'form': project_form, 'goal_id': goal_id, 'project_id': project_id})

def signup(request, token=None):
    logout(request)
    my_email = None
    if token == "None":
        token = None
    if token:
        print("token")
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            username = form.cleaned_data.get('username').strip()
            user.email = username.strip()
            user.save()
            current_site = get_current_site(request)
            user_verified = False

            if not user_verified:
                subject = 'Activate Your Spur Account'
                text = render_to_string('registration/account_activation_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                to_email = To(username)
                content = Content("text/plain", text)
                mail = Mail(from_email=from_email, subject=subject, to_emails=to_email, html_content=content)
                response = sg.client.mail.send.post(mail.get())
                return redirect('account_activation_sent')
            else:
                login(request, user)
                return redirect('giftsharingapp:my-gifts')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form, 'my_email': my_email, 'token': token})


def account_activation_sent(request):
    return render(request, 'registration/account_activation_sent.html')


class ActivateAccountView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.userinfo.email_confirmed = True
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('todoapp:my-goals')
        else:
            # invalid link
            return render(request, 'registration/account_activation_invalid.html')

@csrf_exempt
def accept_invite(request, token=None):
    if token:
        return HttpResponseRedirect(reverse('signup', args=(token,)))
    else:
        invite_id = request.POST.get('invite_id')
        invite = FriendInvite.objects.get(id=invite_id)
    if request.user.id != invite.sent_to_user_id:
        return HttpResponse(
            json.dumps({'result': 'Error'}),
            content_type='application/json'
        )
    success, message = invite.accept_invite()
    response_data = {}
    response_data['redirect_url'] = reverse('giftsharingapp:friends-gifts')
    response_data['message'] = message
    return HttpResponse(
        json.dumps(response_data),
        content_type="application/json"
    )

todoapp/templates/todoapp/edit_project.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
    <div class="row card-body">
        <form
                {% if project_id %}
                    action="{% url 'todoapp:edit_project' goal_id=goal_id project_id=project_id %}"
                {% else %}
                    action="{% url 'todoapp:add_new_project' goal_id=goal_id %}"
                {% endif %}
                    method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            {% if project_id %}
                <input class="btn btn-info" type="submit" value="Edit project">
            {% else %}
                <input class="btn btn-info" type="submit" value="Add project">
            {% endif %}
        </form>
        <input class="btn btn-info" type="button" value="Delete project" onclick="deleteProject({{ project_id }})">
    </div>
{% endblock %}

todoapp/templates/todoapp/goals.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}

    <ol class="card-header breadcrumb row">
        <li class="breadcrumb-item active" aria-current="page">Goals</li>
    </ol>
    <div class="card-body">
        {% for goal in goals %}
            <div class="card container mx-auto">
                <div class="row card-body">
                    <div class="col-2">
                        <span>{{ goal.order_number }}</span>
                    </div>
                    <div class="col-auto">
                        <a href="{% url 'todoapp:show_projects_for_goal' goal_id=goal.id %}">
                            {{ goal.name }}
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="row mx-auto">
        <a href="{% url 'todoapp:show_todays_tasks' %}" type="button" class="btn btn-dark">Conquer Today</a>
    </div>
    <div class="row mx-auto">
        <button type="button" class="btn btn-link">Edit Goals</button>
    </div>

{% endblock %}

todoapp/templates/todoapp/project.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
    <div class="page">
        <form
                {% if project_id %}
                    action="{% url 'todoapp:edit_project' goal_id=goal_id project_id=project_id %}"
                {% else %}
                    action="{% url 'todoapp:add_new_project' goal_id=goal_id %}"
                {% endif %}
                    method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            {% if project_id %}
                <input class="btn btn-info" type="submit" value="Edit project">
            {% else %}
                <input class="btn btn-info" type="submit" value="Add project">
            {% endif %}
        </form>
        <input class="btn btn-info" type="button" value="Delete project" onclick="deleteProject({{ project_id }})">
    </div>
{% endblock %}

todoapp/templates/todoapp/projects.html
{% extends "base_generic.html" %}
{% block content %}
    <ol class="card-header breadcrumb row">
        <li class="breadcrumb-item" aria-current="page">
            <a href="{% url 'todoapp:my-goals' %}">Goals</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">{{ goal.name }}</li>
        <li class="ml-auto">
            <a href="{% url 'todoapp:show_todays_tasks' %}">Today</a>
        </li>
    </ol>
    <div class="ml-auto mr-1">
        <a class="" href="{% url 'todoapp:add_new_project' goal_id=goal.id  %}">
           Add project <i class="fas fa-plus-circle"></i>
        </a>
    </div>

    <div class="card-body container">

        <div class="card-text">
            {% for project_data in projects_data %}
                {% if not project_data.project.status == 'D' %}
                    {% include 'todoapp/subtemplates/project.html' with project_data=project_data %}
                {% endif %}
            {% endfor %}
        </div>
    </div>


{% endblock %}

todoapp/templates/todoapp/task.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
    <div class="page">
        <form
                {% if task_id %}
                    action="{% url 'todoapp:edit_task' project_id=project_id task_id=task_id %}"
                {% else %}
                    action="{% url 'todoapp:add_new_task' project_id=project_id %}"
                {% endif %}
                    method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            {% if task_id %}
                <input class="btn btn-info" type="submit" value="Edit task">
            {% else %}
                <input class="btn btn-info" type="submit" value="Add task">
            {% endif %}
        </form>
        <input class="btn btn-info" type="button" value="Delete task" onclick="deleteTask({{ task_id }})">
    </div>
{% endblock %}

todoapp/templates/todoapp/tasks_for_today.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
    <ol class="card-header breadcrumb row">
        <li class="breadcrumb-item" aria-current="page">
            <a href="{% url 'todoapp:my-goals' %}">Goals</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Today</li>
    </ol>


    <div class="card-body" >
        <div class="mt-2">
            {% for task in today_data.tasks %}
                {% if not task.status == "D" %}
                    <div class="card">
                        <div class="card-body">
{#                            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>#}
                            <div class="row no-gutters font-weight-light align-bottom" style="font-size: 0.5em">
                                <div class="col offset-1 pl-1">
                                    <a href="{% url 'todoapp:show_projects_for_goal' goal_id=task.project.goal.id %}">{{ task.project.goal.name }}</a><span> > </span><a href="{% url 'todoapp:show_projects_for_goal' goal_id=task.project.goal.id %}">{{ task.project.name }}</a>
                                </div>
                            </div>
                            {% include 'todoapp/subtemplates/task.html' with task=task %}
                        </div>
                    </div>

                {% endif %}
            {% endfor %}
        </div>
    </div>

{% endblock %}